name: eventyay-next
region: nyc
services:
- name: eventyay-web
  github:
    branch: test-render-deployment
    deploy_on_push: true
    repo: Abhijeet212004/eventyay
  dockerfile_path: Dockerfile
  source_dir: .
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: EVY_RUNNING_ENVIRONMENT
    value: production
  - key: EVY_SECRET_KEY
    type: SECRET
  - key: EVY_ALLOWED_HOSTS
    value: '["${APP_DOMAIN}"]'
  - key: EVY_SITE_URL
    value: ${APP_URL}
  - key: EVY_DATABASE_URL
    value: ${eventyay-db.DATABASE_URL}
  - key: EVY_REDIS_URL
    value: ${eventyay-redis.REDIS_URL}

workers:
- name: eventyay-worker
  github:
    branch: test-render-deployment
    deploy_on_push: true
    repo: Abhijeet212004/eventyay
  dockerfile_path: Dockerfile
  source_dir: .
  run_command: celery -A eventyay worker -l info
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: EVY_RUNNING_ENVIRONMENT
    value: production
  - key: EVY_SECRET_KEY
    type: SECRET
  - key: EVY_DATABASE_URL
    value: ${eventyay-db.DATABASE_URL}
  - key: EVY_REDIS_URL
    value: ${eventyay-redis.REDIS_URL}

- name: eventyay-scheduler
  github:
    branch: test-render-deployment
    deploy_on_push: true
    repo: Abhijeet212004/eventyay
  dockerfile_path: Dockerfile
  source_dir: .
  run_command: celery -A eventyay beat -l info
  instance_count: 1
  instance_size_slug: basic-xs
  envs:
  - key: EVY_RUNNING_ENVIRONMENT
    value: production
  - key: EVY_SECRET_KEY
    type: SECRET
  - key: EVY_DATABASE_URL
    value: ${eventyay-db.DATABASE_URL}
  - key: EVY_REDIS_URL
    value: ${eventyay-redis.REDIS_URL}

databases:
- name: eventyay-db
  engine: PG
  version: "15"
  production: false
  
- name: eventyay-redis
  engine: REDIS
  version: "7"
  production: true
