name: eventyay-next

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    platform: linux/amd64
    container_name: eventyay-next-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src/eventyay:/usr/src/app/src/eventyay
      - ./webapps/video:/usr/src/app/webapps/video
      - ./webapps/schedule-editor:/usr/src/app/webapps/schedule-editor
      - ./webapps/schedule:/usr/src/app/webapps/schedule
      - ./webapps/webcheckin:/usr/src/app/webapps/webcheckin
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: app/Dockerfile
    platform: linux/amd64
    container_name: eventyay-next-worker
    entrypoint: python -m celery -A eventyay worker -l info
    volumes:
      - ./src/eventyay:/usr/src/app/src/eventyay
      - ./webapps/video:/usr/src/app/webapps/video
      - ./webapps/schedule-editor:/usr/src/app/webapps/schedule-editor
      - ./webapps/schedule:/usr/src/app/webapps/schedule
      - ./webapps/webcheckin:/usr/src/app/webapps/webcheckin
    env_file:
      - ./.env.dev
    environment:
      - MPLCONFIGDIR=/tmp/matplotlib
    depends_on:
      - db
      - redis

  redis:
    image: redis:latest
    platform: linux/amd64
    container_name: eventyay-next-redis
    restart: unless-stopped
    volumes:
      - rd:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]

  db:
    image: postgres:15
    platform: linux/amd64
    container_name: eventyay-next-db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev

volumes:
  postgres_data_dev:
  rd:
