# Zeabur Configuration
# Reference: https://docs.zeabur.com/

services:
  - name: eventyay-web
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - port: 8000
        type: http
    env:
      EVY_RUNNING_ENVIRONMENT: production
      EVY_ALLOWED_HOSTS: '["*"]'
      EVY_SITE_URL: '${ZEABUR_WEB_URL}'
      EVY_DATABASE_URL: '${POSTGRES_URL}'
      EVY_REDIS_URL: '${REDIS_URL}'

  - name: eventyay-worker
    build:
      dockerfile: Dockerfile
      context: .
    startCommand: celery -A eventyay worker -l info
    env:
      EVY_RUNNING_ENVIRONMENT: production
      EVY_DATABASE_URL: '${POSTGRES_URL}'
      EVY_REDIS_URL: '${REDIS_URL}'

  - name: eventyay-scheduler
    build:
      dockerfile: Dockerfile
      context: .
    startCommand: celery -A eventyay beat -l info
    env:
      EVY_RUNNING_ENVIRONMENT: production
      EVY_DATABASE_URL: '${POSTGRES_URL}'
      EVY_REDIS_URL: '${REDIS_URL}'

databases:
  - name: eventyay-db
    type: postgresql

  - name: eventyay-redis
    type: redis
