# Generated by Django 5.2.13 on 2026-05-14 03:26
#
# This data migration calls ``eventyay.plugins.socialauth.secrets`` helpers so ciphertext
# matches runtime encryption. Changing those helpers later does not re-run past migrations.

from django.db import migrations


def encrypt_plaintext_socialapp_secrets(apps, schema_editor):
    from eventyay.plugins.socialauth.secrets import encrypt_secret, is_encrypted_secret

    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    updated = []
    for row in SocialApp.objects.exclude(secret='').iterator():
        secret = row.secret or ''
        if secret and not is_encrypted_secret(secret):
            row.secret = encrypt_secret(secret)
            updated.append(row)
    if updated:
        SocialApp.objects.bulk_update(updated, ['secret'], batch_size=500)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RunPython(encrypt_plaintext_socialapp_secrets, migrations.RunPython.noop),
    ]
