# Generated by Django 5.2.13 on 2026-05-14 03:26
#
# Encryption helpers below are a frozen snapshot for this migration only.
# Do not import eventyay.plugins.socialauth.secrets here.

import base64
import hashlib
import json

from cryptography.fernet import Fernet, InvalidToken, MultiFernet
from django.conf import settings
from django.db import migrations

MIGRATION_SECRET_CONTEXT = 'eventyay.socialauth.secret'
MIGRATION_ENCRYPTED_PREFIX = 'fernet:'
MANAGED_PROVIDERS = frozenset({'github', 'google', 'mediawiki'})
CHUNK_SIZE = 500


def migration_configured_encryption_key_strings():
    raw = settings.SOCIALAUTH_SECRET_ENCRYPTION_KEYS
    if isinstance(raw, str):
        return (raw,) if raw else ()
    if isinstance(raw, (bytes, bytearray)):
        return ()
    if not isinstance(raw, (list, tuple)):
        return ()
    return tuple(key for key in raw if isinstance(key, str) and key)


def migration_derive_fernet_key(source: str) -> bytes:
    digest = hashlib.sha256(f'{MIGRATION_SECRET_CONTEXT}:{source}'.encode('utf-8')).digest()
    return base64.urlsafe_b64encode(digest)


def migration_to_fernet_key(key: str) -> bytes:
    try:
        normalized = key.encode('ascii')
        Fernet(normalized)
        return normalized
    except (UnicodeEncodeError, ValueError):
        return migration_derive_fernet_key(key)


def migration_get_fernet() -> MultiFernet:
    configured_fernet_keys = tuple(
        migration_to_fernet_key(key) for key in migration_configured_encryption_key_strings()
    )
    derived_default_key = migration_derive_fernet_key(settings.SECRET_KEY)
    if derived_default_key in configured_fernet_keys:
        fernet_keys = configured_fernet_keys
    else:
        fernet_keys = configured_fernet_keys + (derived_default_key,)
    return MultiFernet(tuple(Fernet(key) for key in fernet_keys))


def migration_is_encrypted_secret(value: str) -> bool:
    if not value or not value.startswith(MIGRATION_ENCRYPTED_PREFIX):
        return False
    token = value[len(MIGRATION_ENCRYPTED_PREFIX) :]
    try:
        migration_get_fernet().decrypt(token.encode('utf-8'))
        return True
    except InvalidToken:
        return False


def migration_encrypt_secret(value: str) -> str:
    if not value:
        return value
    if migration_is_encrypted_secret(value):
        return value
    if value.startswith(MIGRATION_ENCRYPTED_PREFIX):
        return value
    token = migration_get_fernet().encrypt(value.encode('utf-8')).decode('utf-8')
    return f'{MIGRATION_ENCRYPTED_PREFIX}{token}'


def migration_plaintext_from_stored(value: str) -> str | None:
    """Return plaintext to encrypt, or None when the stored value is unrecoverable."""
    if not value:
        return None
    if migration_is_encrypted_secret(value):
        return migration_decrypt_secret(value) or None
    if value.startswith(MIGRATION_ENCRYPTED_PREFIX):
        return None
    return value


def migration_decrypt_secret(value: str) -> str:
    if not value:
        return value
    if not value.startswith(MIGRATION_ENCRYPTED_PREFIX):
        return value
    token = value[len(MIGRATION_ENCRYPTED_PREFIX) :]
    try:
        return migration_get_fernet().decrypt(token.encode('utf-8')).decode('utf-8')
    except InvalidToken:
        return ''


def migration_load_login_providers(SettingsStore):
    setting = SettingsStore.objects.filter(key='login_providers').first()
    if not setting or not setting.value:
        return {}
    try:
        loaded = json.loads(setting.value)
    except (TypeError, ValueError):
        return {}
    return loaded if isinstance(loaded, dict) else {}


def migration_save_login_providers(SettingsStore, login_providers):
    payload = json.dumps(login_providers)
    setting = SettingsStore.objects.filter(key='login_providers').first()
    if setting:
        setting.value = payload
        setting.save(update_fields=['value'])
    else:
        SettingsStore.objects.create(key='login_providers', value=payload)


def move_socialapp_secrets_to_encrypted_settings(apps, schema_editor):
    """Move provider secrets into encrypted global settings; clear SocialApp.secret.

    One-way migration: legacy SocialApp.secret values are copied into
    ``login_providers`` and then cleared. SocialApp rows remain for allauth
    compatibility but no longer store secrets at rest.
    """
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    SettingsStore = apps.get_model('base', 'GlobalSettingsObject_SettingsStore')

    login_providers = migration_load_login_providers(SettingsStore)
    apps_to_clear = []

    for row in SocialApp.objects.filter(provider__in=MANAGED_PROVIDERS).exclude(secret='').iterator():
        provider_config = login_providers.setdefault(row.provider, {})
        if not isinstance(provider_config, dict):
            provider_config = {}
            login_providers[row.provider] = provider_config

        stored_secret = provider_config.get('secret') or ''
        if stored_secret:
            plaintext = migration_plaintext_from_stored(stored_secret)
        else:
            plaintext = migration_plaintext_from_stored(row.secret or '')

        if plaintext:
            provider_config['secret'] = migration_encrypt_secret(plaintext)

        row.secret = ''
        apps_to_clear.append(row)

    for provider, provider_config in login_providers.items():
        if provider not in MANAGED_PROVIDERS or not isinstance(provider_config, dict):
            continue
        secret = provider_config.get('secret') or ''
        if not secret or migration_is_encrypted_secret(secret):
            continue
        plaintext = migration_plaintext_from_stored(secret)
        if plaintext:
            provider_config['secret'] = migration_encrypt_secret(plaintext)

    migration_save_login_providers(SettingsStore, login_providers)

    if apps_to_clear:
        SocialApp.objects.bulk_update(apps_to_clear, ['secret'], batch_size=CHUNK_SIZE)


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
        ('base', '0027_talkquestion_dependency_question_and_more'),
    ]

    operations = [
        migrations.RunPython(
            move_socialapp_secrets_to_encrypted_settings,
            migrations.RunPython.noop,
        ),
    ]
