# Generated by Django 5.2.13 on 2026-05-14 03:26
#
# Encryption helpers below are a frozen snapshot for this migration only.
# Do not import eventyay.plugins.socialauth.secrets here.

import base64
import hashlib

from cryptography.fernet import Fernet, MultiFernet
from django.conf import settings
from django.db import migrations

_MIGRATION_SECRET_CONTEXT = 'eventyay.socialauth.secret'
_MIGRATION_ENCRYPTED_PREFIX = 'fernet:'
# Keep in sync with SocialAuthApp.ready() (allauth SocialApp.secret max_length patch).
_MIGRATION_SOCIALAPP_SECRET_MAX_LENGTH = 512


def _migration_configured_encryption_key_strings():
    raw = getattr(settings, 'SOCIALAUTH_SECRET_ENCRYPTION_KEYS', ()) or ()
    if isinstance(raw, str):
        return (raw,) if raw else ()
    if isinstance(raw, (bytes, bytearray)):
        return ()
    if not isinstance(raw, (list, tuple)):
        return ()
    return tuple(key for key in raw if isinstance(key, str) and key)


def _migration_derive_fernet_key(source: str) -> bytes:
    digest = hashlib.sha256(f'{_MIGRATION_SECRET_CONTEXT}:{source}'.encode('utf-8')).digest()
    return base64.urlsafe_b64encode(digest)


def _migration_to_fernet_key(key: str) -> bytes:
    try:
        normalized = key.encode('ascii')
        Fernet(normalized)
        return normalized
    except (UnicodeEncodeError, ValueError):
        return _migration_derive_fernet_key(key)


def _migration_get_fernet() -> MultiFernet:
    configured_fernet_keys = tuple(
        _migration_to_fernet_key(key) for key in _migration_configured_encryption_key_strings()
    )
    derived_default_key = _migration_derive_fernet_key(settings.SECRET_KEY)
    if derived_default_key in configured_fernet_keys:
        fernet_keys = configured_fernet_keys
    else:
        fernet_keys = configured_fernet_keys + (derived_default_key,)
    return MultiFernet(tuple(Fernet(key) for key in fernet_keys))


def _migration_is_probably_fernet_token(token: str) -> bool:
    if not token:
        return False
    try:
        padding = '=' * (-len(token) % 4)
        decoded = base64.urlsafe_b64decode(f'{token}{padding}'.encode('ascii'))
    except (UnicodeEncodeError, ValueError):
        return False
    return bool(decoded) and decoded.startswith(b'\x80')


def _migration_is_encrypted_secret(value: str) -> bool:
    if not value:
        return False
    if value.startswith(_MIGRATION_ENCRYPTED_PREFIX):
        return True
    return _migration_is_probably_fernet_token(value)


def _migration_encrypt_secret(value: str) -> str:
    if not value:
        return value
    if value.startswith(_MIGRATION_ENCRYPTED_PREFIX):
        return value
    if _migration_is_probably_fernet_token(value):
        return value
    token = _migration_get_fernet().encrypt(value.encode('utf-8')).decode('utf-8')
    return f'{_MIGRATION_ENCRYPTED_PREFIX}{token}'


def widen_socialapp_secret_max_length(apps, schema_editor):
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    old_field = SocialApp._meta.get_field('secret')
    _, _, args, kwargs = old_field.deconstruct()
    kwargs['max_length'] = _MIGRATION_SOCIALAPP_SECRET_MAX_LENGTH
    new_field = old_field.__class__(*args, **kwargs)
    new_field.set_attributes_from_name('secret')
    new_field.model = SocialApp
    schema_editor.alter_field(SocialApp, old_field, new_field)


def encrypt_plaintext_socialapp_secrets(apps, schema_editor):
    SocialApp = apps.get_model('socialaccount', 'SocialApp')
    secret_field = SocialApp._meta.get_field('secret')
    max_length = secret_field.max_length or _MIGRATION_SOCIALAPP_SECRET_MAX_LENGTH
    updated = []
    for row in SocialApp.objects.exclude(secret='').iterator():
        secret = row.secret or ''
        if secret and not _migration_is_encrypted_secret(secret):
            encrypted = _migration_encrypt_secret(secret)
            if len(encrypted) > max_length:
                raise ValueError(
                    f'SocialApp pk={row.pk} provider={row.provider!r}: encrypted secret length '
                    f'{len(encrypted)} exceeds secret max_length={max_length}. '
                    'Widen socialaccount.SocialApp.secret before running this migration.'
                )
            row.secret = encrypted
            updated.append(row)
    if updated:
        SocialApp.objects.bulk_update(updated, ['secret'], batch_size=500)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socialaccount', '0006_alter_socialaccount_extra_data'),
    ]

    operations = [
        migrations.RunPython(widen_socialapp_secret_max_length, migrations.RunPython.noop),
        migrations.RunPython(encrypt_plaintext_socialapp_secrets, migrations.RunPython.noop),
    ]
