# Generated by Django 5.2.5 on 2025-11-21 10:53

import eventyay.base.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='sidebar_hidden',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, help_text='This image appears at the top of all event pages, replacing the default color or pattern. It is center-aligned and not stretched, ensuring the middle part remains visible on smaller screens. We recommend an image at least 1170 px wide and 120 px in height for best results.', null=True, upload_to=eventyay.base.models.event.event_logo_path, verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('cs', 'Czech'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fr', 'French'), ('it', 'Italian'), ('id', 'Indonesian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('nl', 'Dutch'), ('pt-br', 'Brasilian Portuguese'), ('pt-pt', 'Portuguese'), ('ru', 'Russian'), ('sw', 'Swahili'), ('ua', 'Ukrainian'), ('zh-hant', 'Traditional Chinese (Taiwan)'), ('zh-hans', 'Simplified Chinese')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='When you upload a logo, the event name and date will not appear in the header. The logo scales to 140 px in height while maintaining aspect ratio.', null=True, upload_to=eventyay.base.models.event.event_logo_path, verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('cs', 'Czech'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fr', 'French'), ('it', 'Italian'), ('id', 'Indonesian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('nl', 'Dutch'), ('pt-br', 'Brasilian Portuguese'), ('pt-pt', 'Portuguese'), ('ru', 'Russian'), ('sw', 'Swahili'), ('ua', 'Ukrainian'), ('zh-hant', 'Traditional Chinese (Taiwan)'), ('zh-hans', 'Simplified Chinese')], default='en', max_length=50, verbose_name='Language'),
        ),
    ]
