# Generated by Django 5.2.5 on 2025-11-12 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_sso_username',
            field=models.CharField(
                max_length=255,
                blank=True,
                null=True,
                editable=False,
                verbose_name='Original SSO username',
                help_text='The username from SSO provider at first login. Used for Trust & Safety. Non-editable.'
            ),
        ),
    ]
