# Generated by Django 5.2.5 on 2025-11-12 17:13

import eventyay.base.models.event
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_add_original_sso_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='header_image',
            field=models.ImageField(blank=True, help_text='This image appears at the top of all event pages, replacing the default color or pattern. It is center-aligned and not stretched, ensuring the middle part remains visible on smaller screens. We recommend an image at least 1170 px wide and 120 px in height for best results.', null=True, upload_to=eventyay.base.models.event.event_logo_path, verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, help_text='When you upload a logo, the event name and date will not appear in the header. The logo scales to 140 px in height while maintaining aspect ratio.', null=True, upload_to=eventyay.base.models.event.event_logo_path, verbose_name='Logo'),
        ),
    ]
