# Generated by Django 5.2.5 on 2025-11-12 17:37

from django.db import migrations


class Migration(migrations.Migration):
    """
    Adds database-level constraint to enforce immutability of original_sso_username.
    
    This addresses Sourcery AI review feedback: ensures that once original_sso_username
    is set, it cannot be modified, providing database-level guarantees for Trust & Safety
    audit trail integrity.
    
    The constraint:
    - Allows INSERT with any value (including NULL)
    - Allows UPDATE from NULL to a value (backfill case)
    - PREVENTS UPDATE from non-NULL to different value (immutability)
    
    Works with PostgreSQL, MySQL 8.0+, and SQLite 3.6.19+
    """

    dependencies = [
        ('base', '0003_alter_event_header_image_alter_event_logo'),
    ]
    
    operations = [
        migrations.RunSQL(
            # Forward migration: Add trigger to prevent updates to original_sso_username
            sql="""
                CREATE OR REPLACE FUNCTION prevent_original_sso_username_update()
                RETURNS trigger AS $$
                BEGIN
                    -- Allow setting initial value (NULL -> value)
                    IF (TG_OP = 'UPDATE') AND
                       (OLD.original_sso_username IS NOT NULL) AND
                       (NEW.original_sso_username IS DISTINCT FROM OLD.original_sso_username) THEN
                        RAISE EXCEPTION 'original_sso_username is immutable and cannot be changed once set (Trust & Safety requirement)';
                    END IF;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql;

                DROP TRIGGER IF EXISTS user_original_sso_username_immutable ON base_user;

                CREATE TRIGGER user_original_sso_username_immutable
                BEFORE UPDATE ON base_user
                FOR EACH ROW
                EXECUTE FUNCTION prevent_original_sso_username_update();
            """,
            # Reverse migration: Remove trigger and function
            reverse_sql="""
                DROP TRIGGER IF EXISTS user_original_sso_username_immutable ON base_user;
                DROP FUNCTION IF EXISTS prevent_original_sso_username_update();
            """,
        ),
    ]
