# Generated by Django 5.2.5 on 2025-12-29 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_team_can_video_create_channels_and_more'),
        ('base', '0004_update_team_permission_labels'),
    ]

    operations = [
    ]
