# Generated by Django 5.2.5 on 2025-10-30 15:57

from datetime import timedelta
from django.db import migrations

def fill_date_to(apps, _schema_editor):
    Event = apps.get_model('base', 'Event')
    for event in Event.objects.filter(date_to__isnull=True):
        event.date_to = event.date_from + timedelta(hours=24)
        event.save()
    
    SubEvent = apps.get_model('base', 'SubEvent')
    for event in SubEvent.objects.filter(date_to__isnull=True):
        event.date_to = event.date_from + timedelta(hours=24)
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_logentry_data'),
    ]

    operations = [
        migrations.RunPython(fill_date_to),
    ]
