# Generated by Django 5.2.5 on 2026-01-08 11:22

import django.core.validators
import django.db.models.deletion
import eventyay.base.models.partner
import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team_can_video_create_channels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('ms', 'Malay'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese (Taiwan)')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('ms', 'Malay'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese (Taiwan)')], default='en', max_length=50, verbose_name='Language'),
        ),
        migrations.CreateModel(
            name='PartnerGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(help_text='e.g., "Platinum Sponsors", "Gold Sponsors"', max_length=200, verbose_name='Group name')),
                ('position', models.PositiveIntegerField(default=0, help_text='Groups are displayed in ascending order', verbose_name='Position')),
                ('logo_size', models.PositiveIntegerField(default=160, help_text='Logo height in pixels (50-500)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Logo height (pixels)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_groups', to='base.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Partner Group',
                'verbose_name_plural': 'Partner Groups',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Partner name')),
                ('link', models.URLField(blank=True, help_text='Optional link to partner website', verbose_name='Partner URL')),
                ('logo', models.ImageField(blank=True, help_text='Partner logo image', null=True, upload_to=eventyay.base.models.partner.partner_logo_upload_to, verbose_name='Logo')),
                ('position', models.PositiveIntegerField(default=0, help_text='Partners are displayed in ascending order within their group', verbose_name='Position')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='base.partnergroup', verbose_name='Partner Group')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['position', 'id'],
            },
        ),
    ]
