# Generated by Django 5.2.5 on 2025-01-27 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team_can_video_create_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='min_usages',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of times this voucher must be redeemed before it can be used.', verbose_name='Minimum usages'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='allow_addons',
            field=models.BooleanField(default=False, help_text='If activated, add-on products can be added to the cart for free when this voucher is used.', verbose_name='Allow free add-ons'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='allow_bundled',
            field=models.BooleanField(default=False, help_text='If activated, bundled products will be included when this voucher is used.', verbose_name='Include bundled products'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exhibitor',
            field=models.ForeignKey(blank=True, help_text='Assign this voucher to a specific exhibitor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='base.exhibitor', verbose_name='Exhibitor'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exhibitor_comment',
            field=models.TextField(blank=True, help_text='A comment that will be visible to the assigned exhibitor. This is separate from the internal staff comment.', verbose_name='Exhibitor comment'),
        ),
    ]

