# Generated by Django 5.2.5 on 2026-01-12 13:09

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_team_can_video_create_channels_and_more'),
    ]

    operations = [
            migrations.CreateModel(
                name='EventMessage',
                fields=[
                    ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False)),
                    ('subject', models.CharField(max_length=255)),
                    ('body_text', models.TextField()),
                    ('body_html', models.TextField(blank=True)),
                    ('audience', models.CharField(max_length=32, choices=[
                        ('attendees', 'Attendees'),
                        ('speakers', 'Speakers'),
                        ('staff', 'Staff'),
                        ('all', 'All'),
                    ])),
                    ('state', models.CharField(max_length=16, default='draft', choices=[
                        ('draft', 'Draft'),
                        ('queued', 'Queued'),
                        ('sending', 'Sending'),
                        ('sent', 'Sent'),
                    ])),
                    ('scheduled_at', models.DateTimeField(null=True, blank=True)),
                    ('created_at', models.DateTimeField(auto_now_add=True)),
                    ('event', models.ForeignKey(
                        to='base.event',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='messages',
                    )),
                ],
            ),
            migrations.CreateModel(
                name='EventMessageDelivery',
                fields=[
                    ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, serialize=False)),
                    ('email', models.EmailField(max_length=254)),
                    ('state', models.CharField(max_length=16, default='pending', choices=[
                        ('pending', 'Pending'),
                        ('sent', 'Sent'),
                        ('failed', 'Failed'),
                    ])),
                    ('attempts', models.PositiveIntegerField(default=0)),
                    ('last_error', models.TextField(blank=True)),
                    ('sent_at', models.DateTimeField(null=True, blank=True)),
                    ('message', models.ForeignKey(
                        to='base.eventmessage',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='deliveries',
                    )),
                    ('user', models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='event_message_deliveries',
                    )),
                ],
            ),
    ]

