# Generated by Django 5.2.5 on 2026-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_add_event_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('ms', 'Malay'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese (Taiwan)')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', 'German'), ('de-formal', 'German (formal)'), ('ar', 'Arabic'), ('bg', 'Bulgarian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('da', 'Danish'), ('el', 'Greek'), ('es', 'Spanish'), ('fa-ir', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('hu', 'Hungarian'), ('id', 'Indonesian'), ('it', 'Italian'), ('ja-jp', 'Japanese'), ('ko', 'Korean'), ('lv', 'Latvian'), ('ms', 'Malay'), ('nb-no', 'Norwegian Bokmål'), ('nl', 'Dutch'), ('nl-informal', 'Dutch (informal)'), ('pl', 'Polish'), ('pl-informal', 'Polish (informal)'), ('pt-br', 'Brazilian Portuguese'), ('pt-pt', 'Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('si', 'Sinhala'), ('sl', 'Slovenian'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('th', 'Thai'), ('tr', 'Turkish'), ('uk', 'Ukrainian'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese (Taiwan)')], default='en', max_length=50, verbose_name='Language'),
        ),
        migrations.AlterUniqueTogether(
            name='eventmessagedelivery',
            unique_together={('message', 'email')},
        ),
        migrations.AddIndex(
            model_name='eventmessage',
            index=models.Index(fields=['event'], name='base_eventm_event_i_ef0c64_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmessage',
            index=models.Index(fields=['state'], name='base_eventm_state_6a84f1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmessage',
            index=models.Index(fields=['scheduled_at'], name='base_eventm_schedul_41a7ee_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmessagedelivery',
            index=models.Index(fields=['message'], name='base_eventm_message_825317_idx'),
        ),
        migrations.AddIndex(
            model_name='eventmessagedelivery',
            index=models.Index(fields=['state'], name='base_eventm_state_7f63e9_idx'),
        ),
    ]
