# Generated by Django 5.2.5 on 2026-01-21 22:39

import django.core.validators
import django.db.models.deletion
import eventyay.base.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_landing_page_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., "Platinum Sponsor", "Gold Sponsor"', max_length=200, verbose_name='Group name')),
                ('order', models.IntegerField(default=0, help_text='Groups are displayed in ascending order', verbose_name='Order')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_groups', to='base.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Sponsor group',
                'verbose_name_plural': 'Sponsor groups',
                'ordering': ['order', 'id'],
                'unique_together': {('event', 'name')},
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Partner name')),
                ('link', models.URLField(blank=True, help_text='Optional link to partner website', null=True, verbose_name='Website URL')),
                ('logo', models.ImageField(blank=True, help_text='Partner logo image', null=True, upload_to='partners/%Y/%m/', verbose_name='Logo')),
                ('logo_width', models.IntegerField(default=150, help_text='Maximum width for this partner logo (50-500px)', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)], verbose_name='Logo width (px)')),
                ('order', models.IntegerField(default=0, help_text='Partners are displayed in ascending order within their group', verbose_name='Order')),
                ('sponsor_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='base.sponsorgroup', verbose_name='Sponsor group')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'id'],
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
    ]
