# Generated by Django 5.2.5 on 2025-10-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20251030_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date_to',
            field=models.DateTimeField(verbose_name='Event end time'),
        ),
        migrations.AlterField(
            model_name='subevent',
            name='date_to',
            field=models.DateTimeField(verbose_name='Event end time'),
        ),
    ]
