# Generated by Django 5.2.5 on 2026-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_landing_page_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='featured_order',
            field=models.IntegerField(default=0, help_text='Order in which speakers are displayed (lower numbers appear first)', verbose_name='Display order'),
        ),
        migrations.AddField(
            model_name='speakerprofile',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured speakers will be displayed on the event landing page', verbose_name='Featured speaker'),
        ),
        migrations.AddIndex(
            model_name='speakerprofile',
            index=models.Index(fields=['event', 'is_featured', 'featured_order'], name='speaker_featured_order_idx'),
        ),
    ]
