# Generated by Django 5.2.5 on 2026-01-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_event_locale_alter_user_locale_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='eventmessage',
            index=models.Index(fields=['event', '-created_at'], name='base_eventm_event_i_4e94bd_idx'),
        ),
    ]
