# Generated by Django 5.2.5 on 2026-01-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_speakerprofile_featured_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakerprofile',
            name='featured_order',
            field=models.PositiveSmallIntegerField(default=0, help_text='Order in which speakers are displayed (lower numbers appear first)', verbose_name='Display order'),
        ),
    ]
