# Generated by Django 5.2.10 on 2026-01-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_remove_landing_page_text"),
        ("base", "0007_alter_event_locale_alter_streamschedule_end_time_and_more"),
    ]

    operations = []
