# Generated by Django 5.2.10 on 2026-01-20 19:57

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_merge_20260120_1842"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="This field and its input field are invisible to customers in the public ticket shop. This feature is intended for internal use. Only staff members logged into the control panel can see and fill out this field. The purpose is for internal note taking or tracking information that the customer does not need to see, such as internal seat assignment, VIP status, or internal notes.",
                verbose_name="Hidden field",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="question",
            field=i18nfield.fields.I18nTextField(verbose_name="Custom Field"),
        ),
        migrations.AlterField(
            model_name="question",
            name="required",
            field=models.BooleanField(default=False, verbose_name="Required field"),
        ),
        migrations.AlterField(
            model_name="question",
            name="type",
            field=models.CharField(
                choices=[
                    ("N", "Number"),
                    ("S", "Text (one line)"),
                    ("T", "Multiline text"),
                    ("B", "Confirm Checkbox"),
                    ("C", "Radio button (Choose one option)"),
                    ("M", "Checkbox (Choose one or several options)"),
                    ("F", "File upload"),
                    ("D", "Date"),
                    ("H", "Time"),
                    ("W", "Date and time"),
                    ("CC", "Country code (ISO 3166-1 alpha-2)"),
                    ("TEL", "Phone number"),
                    ("DES", "Text field"),
                ],
                max_length=5,
                verbose_name="Type",
            ),
        ),
    ]
