# Generated by Django 5.2.5 on 2026-01-09 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_voucher_allow_addons_voucher_exhibitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='allow_addons',
            field=models.BooleanField(default=False, help_text='If set, all add-on products can be ordered for free when this voucher is redeemed.', verbose_name='Offer all add-on products for when redeeming this voucher'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='exhibitor',
            field=models.ForeignKey(blank=True, help_text="If this voucher is assigned to an exhibitor, they will be able to see it's usages and have access to attendee data according to your settings.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='base.exhibitor', verbose_name='Exhibitor'),
        ),
    ]
