# Generated by Django 5.2.5 on 2026-01-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkquestion',
            name='contains_personal_data',
            field=models.BooleanField(default=False, help_text='If a user deletes their account, responses containing personal data will be removed, too.', verbose_name='Responses contain personal data'),
        ),
    ]
