# Generated by Django 5.2.10 on 2026-01-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
