# Generated by Django 5.2.10 on 2026-01-24 20:05

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkquestion',
            name='question',
            field=i18nfield.fields.I18nCharField(default='', max_length=800, verbose_name='Label'),
            preserve_default=False,
        ),
    ]
