# Generated by Django 5.2.10 on 2026-01-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='The position field is used to determine the order that session types are displayed in (lowest first).', null=True),
        ),
    ]
