# Generated by Django 5.2.10 on 2026-01-25 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='allow_addons',
            field=models.BooleanField(default=False, help_text='If set, all add-on products can be ordered for free when this voucher is redeemed.', verbose_name='Offer all add-on products for when redeeming this voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='allow_bundled',
            field=models.BooleanField(default=False, help_text='If activated, bundled products will be included when this voucher is used.', verbose_name='Include bundled products'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exhibitor',
            field=models.ForeignKey(blank=True, help_text="If this voucher is assigned to an exhibitor, they will be able to see it's usages and have access to attendee data according to your settings.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='base.exhibitor', verbose_name='Exhibitor'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='exhibitor_comment',
            field=models.TextField(blank=True, help_text='A comment that will be visible to the assigned exhibitor. This is separate from the internal staff comment.', verbose_name='Exhibitor comment'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='min_usages',
            field=models.PositiveIntegerField(default=0, help_text='Minimum number of eligible products required in the cart for this voucher to be applied.', verbose_name='Minimum usages'),
        ),
    ]
