# Generated by Django 5.2.5 on 2026-01-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_private_testmode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email',
            field=models.EmailField(
                blank=True,
                help_text="Enter an organiser email address for event-related emails. When the platform sender is used, this address will be used as the Reply-To. If left empty, emails will be sent using the platform's default email address.",
                max_length=254,
                null=True,
                verbose_name='Organizer email address'
            ),
        ),
    ]
