# Generated by Django 5.2.10 on 2026-01-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_talkquestion_contains_personal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, help_text='Inactive questions are not shown to customers during checkout or check-in. Unlike hidden questions (which are system-level), active controls visibility and can be toggled by event organizers.', verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='variant',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text (one-line)'), ('text', 'Multi-line text'), ('url', 'URL'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Confirmation'), ('file', 'File upload'), ('choices', 'Radio button (Choose one option)'), ('multiple_choice', 'Checkbox (Choose one or several options)')], default='string', max_length=15),
        ),
    ]
