# Generated by Django 5.2.10 on 2026-01-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_talkquestion_contains_personal_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
