# Generated by Django 5.2.10 on 2026-01-27 13:28

from django.db import migrations, models


def populate_position_values(apps, schema_editor):
    """Backfill position values based on existing default_duration order"""
    SubmissionType = apps.get_model('base', 'SubmissionType')
    
    # Get all unique event IDs
    events = SubmissionType.objects.values_list('event_id', flat=True).distinct()
    
    for event_id in events:
        # Get types for this event, ordered by default_duration then id
        types = list(
            SubmissionType.objects.filter(event_id=event_id).order_by('default_duration', 'id')
        )
        # Assign positions starting from 1
        for index, submission_type in enumerate(types, start=1):
            submission_type.position = index
        
        # Bulk update for performance
        SubmissionType.objects.bulk_update(types, ['position'])


def reverse_populate(apps, schema_editor):
    """Reverse operation - set all positions back to 0"""
    SubmissionType = apps.get_model('base', 'SubmissionType')
    SubmissionType.objects.all().update(position=0)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_private_testmode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='The position field is used to determine the order that session types are displayed in (lowest first).'),
        ),
        migrations.RunPython(populate_position_values, reverse_populate),
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'ordering': ('position',)},
        ),
    ]
