# Generated by Django 5.2.10 on 2026-01-29 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_private_testmode_and_more'),
        ('base', '0009_voucher_allow_addons_voucher_allow_bundled_and_more'),
    ]

    operations = [
    ]
