# Generated by Django 5.2.10 on 2026-01-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_question_hidden_alter_question_question_and_more"),
        ("base", "0009_event_private_testmode_and_more"),
    ]

    operations = []
