# Generated by Django 5.2.10 on 2026-01-26 11:25

from django.db import migrations, models


def populate_position_values(apps, schema_editor):
    SubmissionType = apps.get_model('base', 'SubmissionType')
    
    # Group by event to ensure positions are scoped per event
    from django.db.models import Q
    events = SubmissionType.objects.values_list('event_id', flat=True).distinct()
    
    for event_id in events:
        types = SubmissionType.objects.filter(event_id=event_id).order_by('default_duration', 'id')
        for index, submission_type in enumerate(types, start=1):
            submission_type.position = index
            submission_type.save(update_fields=['position'])


def reverse_populate(apps, schema_editor):
    SubmissionType = apps.get_model('base', 'SubmissionType')
    SubmissionType.objects.all().update(position=None)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('base', '0008_make_custom_field_label_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissiontype',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='The position field is used to determine the order that session types are displayed in (lowest first).', null=True),
        ),
        migrations.RunPython(populate_position_values, reverse_populate),
        migrations.AlterField(
            model_name='submissiontype',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='The position field is used to determine the order that session types are displayed in (lowest first).'),
        ),
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'ordering': ('position',)},
        ),
    ]
