# Generated by Django 5.2.10 on 2026-01-31 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_queuedmail_scheduled_at'),
        ('base', '0010_question_active'),
    ]

    operations = [
    ]
