# Generated by Django 5.2.10 on 2026-02-02 00:10

import i18nfield.fields
import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='review',
            field=tinymce.models.HTMLField(verbose_name='Feedback'),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='What do you think?'),
        ),
        migrations.AlterField(
            model_name='speakerprofile',
            name='biography',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Biography'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='abstract',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Abstract'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=tinymce.models.HTMLField(blank=True, help_text='These notes are meant for the organiser and won’t be made public.', null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='submissioncomment',
            name='text',
            field=tinymce.models.HTMLField(verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_license',
            field=tinymce.models.HTMLField(blank=True, help_text='Please enter the name of the license of the photo and link to it if applicable.', null=True, verbose_name='Profile Picture License'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_source',
            field=tinymce.models.HTMLField(blank=True, help_text='Please enter the name of the author or source of image and a link if applicable.', null=True, verbose_name='Profile Picture Source'),
        ),
        migrations.AlterField(
            model_name='cfp',
            name='text',
            field=i18nfield.fields.I18nTextField(blank=True, null=True, verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='event',
            name='featured_sessions_text',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='Shown at the top of the featured sessions page.', null=True, verbose_name='Featured sessions text'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='comment',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='Shown publicly in the changelog and RSS feed.', null=True),
        ),
        migrations.AlterField(
            model_name='speakerinformation',
            name='text',
            field=i18nfield.fields.I18nTextField(verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='help_text',
            field=i18nfield.fields.I18nCharField(blank=True, help_text='Shown below the input field as guidance.', max_length=800, null=True, verbose_name='help text'),
        ),
    ]
