# Generated by Django 5.2.10 on 2026-02-01 21:15

import i18nfield.fields
from django.db import migrations



def backfill_nulls(apps, schema_editor):
    TalkQuestion = apps.get_model('base', 'TalkQuestion')
    TalkQuestion.objects.filter(question__isnull=True).update(question="")


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_question_active'),
    ]

    operations = [
        migrations.RunPython(backfill_nulls, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='talkquestion',
            name='question',
            field=i18nfield.fields.I18nCharField(max_length=800, verbose_name='Custom question'),
        ),
    ]
