# Generated by Django 5.2.10 on 2026-02-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_event_talks_published_event_tickets_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='not_on_frontpage',
            field=models.BooleanField(default=False, help_text='If selected, this event will not be listed on the public frontpage.', verbose_name='Not on Front Page'),
        ),
    ]
