# Generated by Django 5.2.10 on 2026-02-05 13:51

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_event_startpage_featured_event_startpage_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkquestion',
            name='question',
            field=i18nfield.fields.I18nCharField(default='', max_length=800, verbose_name='Custom question'),
            preserve_default=False,
        ),
    ]
