# Generated by Django 5.2.10 on 2026-02-05 13:51

import i18nfield.fields
from django.db import migrations

def backfill_question(apps, schema_editor):
    """
    Backfill NULL `question` values to empty strings before altering the field,
    ensuring existing rows comply with the new default/non-null semantics.
    """
    TalkQuestion = apps.get_model('base', 'TalkQuestion')
    queryset = TalkQuestion.objects.filter(question__isnull=True)
    for talk_question in queryset.iterator():
        talk_question.question = ''
        talk_question.save(update_fields=['question'])


def reverse_backfill_question(apps, schema_editor):
    """
    Reverse the backfill by setting empty question values back to NULL.
    This allows safer rollback during deployment if issues are discovered.
    """
    TalkQuestion = apps.get_model('base', 'TalkQuestion')
    queryset = TalkQuestion.objects.filter(question='')
    for talk_question in queryset.iterator():
        talk_question.question = None
        talk_question.save(update_fields=['question'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_event_startpage_featured_event_startpage_visible'),
    ]

    operations = [
        migrations.RunPython(backfill_question, reverse_backfill_question),
        migrations.AlterField(
            model_name='talkquestion',
            name='question',
            field=i18nfield.fields.I18nCharField(default='', max_length=800, verbose_name='Custom question'),
            preserve_default=False,
        ),
    ]
