# Generated by Django 5.2.10 on 2026-01-23 14:19
#
# Parent question deletion behavior:
# - on_delete=SET_NULL ensures dependent questions remain intact when parent is deleted
# - The dependency_question field becomes NULL, effectively disabling the dependency
# - Dependent questions become visible to all users (no longer conditionally shown)
# - This prevents data loss and allows organizers to reassign dependencies if needed

import django.db.models.deletion
import eventyay.base.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_talkquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkquestion',
            name='dependency_question',
            field=models.ForeignKey(blank=True, help_text='This field will only be shown if the selected field has one of the specified values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='base.talkquestion', verbose_name='Custom field dependency'),
        ),
        migrations.AddField(
            model_name='talkquestion',
            name='dependency_values',
            field=eventyay.base.models.fields.MultiStringField(default=list, verbose_name='Dependency values'),
        ),
    ]
