# Generated by Django 5.2.10 on 2026-02-07 09:10

from django.db import migrations, models


def set_initial_positions(apps, schema_editor):
    SubmissionType = apps.get_model('base', 'SubmissionType')
    Event = apps.get_model('base', 'Event')
    
    for event in Event.objects.all():
        types = list(SubmissionType.objects.filter(event=event).order_by('default_duration', 'pk'))
        for index, submission_type in enumerate(types):
            submission_type.position = index
        if types:
            SubmissionType.objects.bulk_update(types, ['position'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_talkquestion_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submissiontype',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='submissiontype',
            name='position',
            field=models.PositiveIntegerField(blank=True, help_text='The position field is used to determine the order that session types are displayed in (lowest first).', null=True),
        ),
        migrations.RunPython(set_initial_positions, migrations.RunPython.noop),
    ]
