# Generated by Django 5.2.11 on 2026-02-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_talkquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='link_in_system',
            field=models.BooleanField(default=True, verbose_name='Show in header and footer on system pages'),
        ),
    ]
