# Generated by Django 5.2.9 on 2026-02-07 09:50

from django.db import migrations, models


def backfill_positions(apps, _schema_editor):
    """Backfill position values for existing SubmissionType instances.

    Sets position based on current default_duration ordering to maintain
    stable order and prevent NULL-related ordering issues.
    """
    SubmissionType = apps.get_model('base', 'SubmissionType')
    Event = apps.get_model('base', 'Event')

    for event in Event.objects.all():
        # Get all submission types for this event, ordered by default_duration
        types = SubmissionType.objects.filter(event=event).order_by('default_duration', 'id')

        # Assign positions starting from 1
        for position, submission_type in enumerate(types, start=1):
            submission_type.position = position
            submission_type.save(update_fields=['position'])


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_talkquestion_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submissiontype",
            options={"ordering": ["position", "default_duration"]},
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The position field is used to determine the order that session types are displayed in (lowest first).",
                null=True,
                verbose_name="position",
            ),
        ),
        migrations.RunPython(backfill_positions, reverse_code=migrations.RunPython.noop),
    ]
