# Generated by Django 5.2.9 on 2026-02-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0013_alter_talkquestion_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="submissiontype",
            options={"ordering": ["position", "default_duration"]},
        ),
        migrations.AddField(
            model_name="submissiontype",
            name="position",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="The position field is used to determine the order that session types are displayed in (lowest first).",
                null=True,
                verbose_name="position",
            ),
        ),
    ]
