# Generated by Django 5.2.11 on 2026-02-16 07:45

import i18nfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_talkquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkin_text',
            field=i18nfield.fields.I18nTextField(blank=True, help_text='This text will be displayed by the check-in app when a ticket of this type is scanned.', null=True, verbose_name='Check-in text'),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='If set, tickets of this product will only be valid from this date and time.', null=True, verbose_name='Start of validity'),
        ),
        migrations.AddField(
            model_name='product',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='If set, tickets of this product will only be valid until this date and time.', null=True, verbose_name='End of validity'),
        ),
        migrations.AddField(
            model_name='product',
            name='validity_type',
            field=models.CharField(choices=[('default', 'Default (determined by event and check-in configuration)'), ('fixed', 'Fixed time frame')], default='default', help_text='For regular events, you typically do not need to change this value. The default means that validity is determined by the event and check-in configuration, not by the product itself. Note that validity is stored with the ticket, so changes here will not affect existing tickets.', max_length=10, verbose_name='Validity'),
        ),
    ]
