# Generated by Django 5.2 on 2026-02-07
# Create PeriodicTask for send_periodic_signal to enable email scheduling

from django.db import migrations
from django.utils.timezone import now


def create_periodic_task(apps, schema_editor):
    """Create PeriodicTask to trigger send_periodic_signal every 60 seconds."""
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    IntervalSchedule = apps.get_model('django_celery_beat', 'IntervalSchedule')
    
    # Create interval: every 60 seconds
    interval, _ = IntervalSchedule.objects.get_or_create(
        every=60,
        period='seconds',
    )
    
    # Create PeriodicTask for send_periodic_signal
    PeriodicTask.objects.get_or_create(
        name='send_periodic_signal',
        defaults={
            'task': 'eventyay.common.tasks.send_periodic_signal',
            'interval': interval,
            'enabled': True,
            'start_time': now(),
        }
    )


def remove_periodic_task(apps, schema_editor):
    """Remove the PeriodicTask when reversing this migration."""
    PeriodicTask = apps.get_model('django_celery_beat', 'PeriodicTask')
    PeriodicTask.objects.filter(name='send_periodic_signal').delete()


class Migration(migrations.Migration):
    dependencies = [
        ('base', '0014_queuedmail_scheduled_at'),
    ]

    operations = [
        migrations.RunPython(create_periodic_task, remove_periodic_task),
    ]
