# Generated by Django on 2026-02-25 12:30

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_submissiontype_position_cfp_default_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='pseudonymization_id',
            field=models.CharField(max_length=16, db_index=True),
        ),
        migrations.AlterField(
            model_name='orderposition',
            name='secret',
            field=models.CharField(max_length=255, db_index=True),
        ),
    ]
