# Generated by Django 5.2.11 on 2026-03-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_event_locale_alter_user_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='bypass_approval',
            field=models.BooleanField(default=False, help_text='If activated, orders using this voucher will be automatically approved and will not enter the pending approval state, even if the product normally requires approval.', verbose_name='Bypass approval requirement'),
        ),
    ]
