# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_event_locale_alter_user_locale'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('general', 'General event'),
                    ('conference', 'Conference'),
                    ('exhibition', 'Exhibition / Trade show'),
                ],
                default='general',
                help_text='Event type affects which features and metadata are shown (e.g. industry sector for trade shows).',
                max_length=20,
                verbose_name='Event type',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='industry_sector',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '— Not specified —'),
                    ('manufacturing', 'Manufacturing'),
                    ('healthcare', 'Healthcare'),
                    ('technology', 'Technology'),
                    ('logistics', 'Logistics'),
                    ('retail', 'Retail'),
                    ('energy', 'Energy'),
                    ('automotive', 'Automotive'),
                    ('food_beverage', 'Food & Beverage'),
                    ('construction', 'Construction'),
                    ('finance', 'Finance'),
                    ('other', 'Other'),
                ],
                default='',
                help_text='Optional. Main industry or sector (especially relevant for exhibitions and trade shows).',
                max_length=30,
                verbose_name='Industry / sector',
            ),
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_frequency',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'One-off event'),
                    ('annual', 'Annual (recurring every year)'),
                    ('biennial', 'Biennial (recurring every two years)'),
                ],
                default='',
                help_text='Whether this event recurs at the same venue (e.g. annual trade show).',
                max_length=20,
                verbose_name='Recurrence',
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_type',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', '— Default (attendee) —'),
                    ('attendee', 'Attendee'),
                    ('exhibitor', 'Exhibitor'),
                    ('buyer', 'Buyer'),
                    ('press', 'Press'),
                    ('vip', 'VIP'),
                ],
                default='',
                help_text='Optional. For trade shows and exhibitions: use this to distinguish exhibitor, buyer, press, or VIP tickets for badge printing and access control.',
                max_length=20,
                verbose_name='Badge / attendee type',
            ),
        ),
    ]
