# Generated by Django 5.2.11 on 2026-03-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_event_locale_alter_user_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderposition',
            name='pseudonymization_id',
            field=models.CharField(db_index=True, max_length=16),
        ),
    ]
