# Generated by Django 5.2.12 on 2026-04-16 03:22

from django.db import migrations


def migrate_meta_noindex(apps, schema_editor):
    Event_SettingsStore = apps.get_model('base', 'Event_SettingsStore')
    for setting in Event_SettingsStore.objects.filter(key='meta_noindex'):
        if setting.value in ('True', 'true', '"True"', '"true"'):
            event = setting.object
            if event.display_settings is None:
                event.display_settings = {}
            # Only update if it's not already set
            if 'meta_noindex' not in event.display_settings:
                event.display_settings['meta_noindex'] = True
                event.save(update_fields=['display_settings'])

        # We can also delete the old setting
        setting.delete()


def reverse_migrate_meta_noindex(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_event_featured_sessions_text'),
    ]

    operations = [
        migrations.RunPython(migrate_meta_noindex, reverse_migrate_meta_noindex),
    ]
