# Generated by Django 5.2 on 2026-04-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_remove_event_featured_sessions_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talkquestion',
            name='variant',
            field=models.CharField(
                choices=[
                    ('number', 'Number'),
                    ('string', 'Text (one-line)'),
                    ('text', 'Multi-line text'),
                    ('url', 'URL'),
                    ('date', 'Date'),
                    ('datetime', 'Date and time'),
                    ('boolean', 'Confirmation'),
                    ('file', 'File upload'),
                    ('choices', 'Radio button (Choose one option)'),
                    ('multiple_choice', 'Checkbox (Choose one or several options)'),
                    ('select', 'Select (one option)'),
                    ('country', 'Country List'),
                ],
                default='string',
                max_length=15,
            ),
        ),
    ]
