# Generated by Django 5.2.11 on 2026-05-07 14:00

import django.db.models.deletion
import eventyay.base.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_resource_kind_talkquestion_import_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='talkquestion',
            name='dependency_question',
            field=models.ForeignKey(blank=True, help_text='This field will only be shown if the selected field has one of the specified values.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_questions', to='base.talkquestion', verbose_name='Custom field dependency'),
        ),
        migrations.AddField(
            model_name='talkquestion',
            name='dependency_values',
            field=eventyay.base.models.fields.MultiStringField(default=list, verbose_name='Dependency values'),
        ),
    ]
