# Generated by Django 5.2 on 2026-04-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_talkquestion_variant_add_select'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='free_price_max',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The maximum price a user can enter. If left empty, there is no upper limit.', max_digits=7, null=True, verbose_name='Maximum price'),
        ),
        migrations.AddField(
            model_name='product',
            name='free_price_min',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The minimum price a user has to enter. If left empty, the default price will be used as the minimum.', max_digits=7, null=True, verbose_name='Minimum price'),
        ),
    ]
