# Generated by Django 5.2.12 on 2026-04-16 03:22

from django.db import migrations


_TRUTHY_VALUES = frozenset({'True', 'true', '"True"', '"true"', '1', 'yes', 'on', '"1"', '"yes"', '"on"'})
_CHUNK_SIZE = 1000


def _chunks(items, size):
    for index in range(0, len(items), size):
        yield items[index : index + size]


def migrate_meta_noindex(apps, schema_editor):
    Event = apps.get_model('base', 'Event')
    Event_SettingsStore = apps.get_model('base', 'Event_SettingsStore')

    events_to_update = {}
    settings_to_delete = []

    for setting in Event_SettingsStore.objects.filter(key='meta_noindex').iterator(chunk_size=_CHUNK_SIZE):
        settings_to_delete.append(setting.pk)
        if setting.value not in _TRUTHY_VALUES:
            continue
        event = setting.object
        display_settings = event.display_settings
        if display_settings is None:
            display_settings = {}
        elif not isinstance(display_settings, dict):
            display_settings = dict(display_settings)
        else:
            display_settings = dict(display_settings)
        if display_settings.get('meta_noindex') is True:
            continue
        display_settings['meta_noindex'] = True
        event.display_settings = display_settings
        events_to_update[event.pk] = event

    if events_to_update:
        Event.objects.bulk_update(events_to_update.values(), ['display_settings'], batch_size=_CHUNK_SIZE)

    for chunk in _chunks(settings_to_delete, _CHUNK_SIZE):
        Event_SettingsStore.objects.filter(pk__in=chunk).delete()


def reverse_migrate_meta_noindex(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_talkquestion_dependency_question_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_meta_noindex, reverse_migrate_meta_noindex),
    ]
