# Generated by Django 5.2.13 on 2026-05-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_talkquestion_dependency_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_video_manage_polls_questions',
            field=models.BooleanField(default=False, help_text='Allows managing polls and questions in rooms inside Eventyay Video.', verbose_name='Video: Can manage polls and questions'),
        ),
    ]
