# Generated by Django 5.2.13 on 2026-05-25 18:51

import eventyay.helpers.countries
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_talkquestion_dependency_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFeeCountrySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', eventyay.helpers.countries.FastCountryField(countries=eventyay.helpers.countries.CachedCountries, max_length=2, unique=True, verbose_name='Country')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency')),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Service fee percentage')),
                ('max_fee', models.DecimalField(decimal_places=2, help_text='Set to 0 for no limit.', max_digits=13, verbose_name='Maximum fee')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country fee setting',
                'verbose_name_plural': 'Country fee settings',
                'ordering': ('country',),
            },
        ),
    ]
