# Generated by Django 5.2.13 on 2026-05-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_talkquestion_dependency_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set, the email will be sent at this time instead of immediately.', null=True, verbose_name='Scheduled for'),
        ),
    ]
