# Generated by Django 5.2.12 on 2026-04-16 03:22

import json

from django.db import migrations


# Hierarkey stores bool settings as plain strings in Event_SettingsStore.value.
# Cover the variants observed in production and in hierarkey defaults (e.g. 'True').
_TRUTHY_VALUES = frozenset({'True', 'true', '"True"', '"true"', '1', 'yes', 'on', '"1"', '"yes"', '"on"'})


def _setting_is_truthy(value: str) -> bool:
    if value in _TRUTHY_VALUES:
        return True
    try:
        return json.loads(value) is True
    except (TypeError, ValueError):
        return False


_CHUNK_SIZE = 1000


def _flush_events_to_update(Event, events_to_update):
    if not events_to_update:
        return
    Event.objects.bulk_update(
        events_to_update.values(),
        ['display_settings'],
        batch_size=_CHUNK_SIZE,
    )
    events_to_update.clear()


def migrate_meta_noindex(apps, schema_editor):
    Event = apps.get_model('base', 'Event')
    Event_SettingsStore = apps.get_model('base', 'Event_SettingsStore')

    events_to_update = {}

    for setting in (
        Event_SettingsStore.objects.filter(key='meta_noindex')
        .select_related('object')
        .iterator(chunk_size=_CHUNK_SIZE)
    ):
        if not _setting_is_truthy(setting.value):
            continue
        event = setting.object
        display_settings = event.display_settings
        display_settings = dict(display_settings) if display_settings is not None else {}
        if display_settings.get('meta_noindex') is True:
            continue
        display_settings['meta_noindex'] = True
        event.display_settings = display_settings
        events_to_update[event.pk] = event
        if len(events_to_update) >= _CHUNK_SIZE:
            _flush_events_to_update(Event, events_to_update)

    _flush_events_to_update(Event, events_to_update)

    # Remove all legacy meta_noindex rows, including falsy values skipped above.
    # False is the default in display_settings; those rows are obsolete after migration.
    while True:
        pks = list(
            Event_SettingsStore.objects.filter(key='meta_noindex')
            .values_list('pk', flat=True)[:_CHUNK_SIZE]
        )
        if not pks:
            break
        Event_SettingsStore.objects.filter(pk__in=pks).delete()


class Migration(migrations.Migration):
    # One-way migration: forward copies meta_noindex into display_settings and
    # deletes legacy Event_SettingsStore rows. Reversing cannot restore the rows.

    dependencies = [
        ('base', '0028_product_free_price_max_product_free_price_min'),
    ]

    operations = [
        migrations.RunPython(migrate_meta_noindex, migrations.RunPython.noop),
    ]
