# Generated by Django 5.2.14 on 2026-06-03 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_free_price_max_product_free_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Spam accounts are blocked from logging in but remain in the database.', verbose_name='Is marked as spam'),
        ),
        migrations.AlterField(
            model_name='product',
            name='free_price',
            field=models.BooleanField(default=False, help_text='If this option is active, your users can choose the price themselves. The minimum and maximum prices can be configured below. If not configured, the default price is used as the minimum. You could use this e.g. to collect additional donations for your event. This is currently not supported for products that are bought as an add-on to other products.', verbose_name='Free price input'),
        ),
    ]
