# Generated by Django 5.2.14 on 2026-06-06 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_free_price_max_product_free_price_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Spam accounts are blocked from logging in but remain in the database.', verbose_name='Is marked as spam'),
        ),
    ]
