# Generated by Django 5.2.13 on 2026-06-01 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_product_free_price_max_product_free_price_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Spam accounts are blocked from logging in but remain in the database.', verbose_name='Is marked as spam'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether this user has been manually verified by an admin.', verbose_name='Is verified'),
        ),
    ]
