# Generated by Django 5.2.15 on 2026-06-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_room_is_unscheduled_team_polls_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizerfollower',
            name='muted',
            field=models.BooleanField(default=False, verbose_name='Muted'),
        ),
    ]
