# Generated by Django 5.2.14 on 2026-06-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_room_is_unscheduled_team_polls_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuedmail',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='If set, the email will be sent at this time instead of immediately.', null=True, verbose_name='Scheduled for'),
        ),
    ]
