# Generated by Django 5.2.15 on 2026-06-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_migrate_meta_noindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_spam',
            field=models.BooleanField(default=False, help_text='Spam accounts are blocked from logging in but remain in the database.', verbose_name='Is marked as spam'),
        ),
    ]
