# Generated by Django 5.2.14 on 2026-06-16

from django.db import migrations, models


def migrate_native_stream_schedules(apps, schema_editor):
    StreamSchedule = apps.get_model('base', 'StreamSchedule')
    StreamSchedule.objects.filter(stream_type='native').update(stream_type='hls')


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_migrate_meta_noindex'),
    ]

    operations = [
        migrations.RunPython(
            migrate_native_stream_schedules,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='streamschedule',
            name='stream_type',
            field=models.CharField(
                choices=[
                    ('youtube', 'YouTube'),
                    ('vimeo', 'Vimeo'),
                    ('hls', 'HLS'),
                    ('iframe', 'Iframe'),
                ],
                default='youtube',
                max_length=50,
                verbose_name='Stream Type',
            ),
        ),
    ]
