# Generated by Django 5.2.13 on 2026-06-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_alter_event_private_testmode_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('app_id', models.CharField(max_length=200)),
                ('app_secret', models.CharField(max_length=300)),
                ('key_id', models.CharField(blank=True, max_length=200)),
                ('event_exclusive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.event')),
            ],
        ),
    ]
