# Generated by Django 5.2.15 on 2026-06-30 15:05

import django.contrib.postgres.indexes
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_checkin_admission_and_devices'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='orderposition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attendee_name_cached'], name='orderpos_name_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='orderposition',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attendee_email'], name='orderpos_email_trgm', opclasses=['gin_trgm_ops']),
        ),
    ]
