# Generated by Django 5.2.15 on 2026-07-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_team_force_hide_speaker_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queuedmail',
            name='reply_to',
            field=models.CharField(blank=True, help_text='By default, the organizer email is used as Reply-To when the platform sender is used. With a custom sender, replies go to the sender address unless overridden here.', max_length=1000, null=True, verbose_name='Reply-To'),
        ),
    ]
