# Generated by Django 5.2.15 on 2026-07-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_team_can_manage_bank_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='all_teamshifts_roles',
            field=models.BooleanField(default=True, verbose_name='All teamshifts roles'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_teamshifts_create_roles',
            field=models.BooleanField(default=False, verbose_name='Can create roles'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_teamshifts_create_shifts',
            field=models.BooleanField(default=False, verbose_name='Can create and edit shifts'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_teamshifts_manage_applicants',
            field=models.BooleanField(default=False, verbose_name='Can manage applicants (accept/reject)'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_teamshifts_send_emails',
            field=models.BooleanField(default=False, verbose_name='Can send custom emails'),
        ),
        migrations.AddField(
            model_name='team',
            name='can_teamshifts_view_email_addresses',
            field=models.BooleanField(default=False, verbose_name='Can view volunteer email addresses'),
        ),
        migrations.AddField(
            model_name='team',
            name='limit_teamshifts_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='Limit teamshifts roles'),
        ),
    ]
