# Generated by Django 5.2.16 on 2026-07-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0047_remove_order_order_code_trgm_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="can_manage_social_media",
            field=models.BooleanField(
                default=False,
                help_text="Allows members of this team to connect social media accounts, manage draft posts, and automate social media publications.",
                verbose_name="Can manage social media settings",
            ),
        ),
    ]
