# Generated by Django 5.2.13 on 2026-06-28

import uuid

import django.db.models.deletion
from django.db import migrations, models


JITSI_ROLE_PERMISSION_AUGMENTS = {
    'participant': ['room:jitsi.join'],
    'room_owner': ['room:jitsi.join', 'room:jitsi.moderate'],
    'speaker': ['room:jitsi.join', 'room:jitsi.moderate'],
    'moderator': ['room:jitsi.join', 'room:jitsi.moderate'],
    'admin': [
        'room:jitsi.join',
        'room:jitsi.moderate',
        'event:rooms.create.jitsi',
    ],
    'apiuser': [
        'room:jitsi.join',
        'room:jitsi.moderate',
        'event:rooms.create.jitsi',
    ],
}


def add_jitsi_permissions_to_roles(apps, schema_editor):
    Event = apps.get_model('base', 'Event')
    World = apps.get_model('base', 'World')
    for model in (Event, World):
        for obj in model.objects.exclude(roles__isnull=True):
            roles = obj.roles or {}
            changed = False
            for role, permissions in JITSI_ROLE_PERMISSION_AUGMENTS.items():
                role_permissions = roles.get(role)
                if role_permissions is None:
                    continue
                for permission in permissions:
                    if permission not in role_permissions:
                        role_permissions.append(permission)
                        changed = True
            if changed:
                obj.save(update_fields=['roles'])


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_checkin_list_limits_and_popup_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='JitsiServer',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField()),
                ('app_id', models.CharField(max_length=200)),
                ('app_secret', models.CharField(max_length=300)),
                ('key_id', models.CharField(blank=True, max_length=200)),
                (
                    'event_exclusive',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to='base.event',
                    ),
                ),
            ],
        ),
        migrations.RunPython(
            add_jitsi_permissions_to_roles,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
