# Generated by Django 5.2.15 on 2026-08-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_consolidate_video_team_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='can_create_meetups',
            field=models.BooleanField(default=False, help_text='Allows members to create meetup events for this organizer.', verbose_name='Can create meetup events'),
        ),
    ]
