# Generated by Django 5.2.13 on 2026-08-09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0051_consolidate_video_team_permissions'),
        ('base', '0051_jitsiserver'),
    ]

    operations = []
