# Generated by Django 6.0.7 on 2026-08-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_alter_locale_choices_native_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibitor',
            name='event',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='highlighted_room',
        ),
        migrations.RemoveField(
            model_name='exhibitor',
            name='room',
        ),
        migrations.RemoveField(
            model_name='exhibitorsocialmedialink',
            name='exhibitor',
        ),
        migrations.RemoveField(
            model_name='exhibitorlink',
            name='exhibitor',
        ),
        migrations.RemoveField(
            model_name='exhibitorview',
            name='exhibitor',
        ),
        migrations.RemoveField(
            model_name='exhibitorstaff',
            name='exhibitor',
        ),
        migrations.AlterUniqueTogether(
            name='exhibitorstaff',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='exhibitorstaff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exhibitorview',
            name='user',
        ),
        migrations.DeleteModel(
            name='ContactRequest',
        ),
        migrations.DeleteModel(
            name='ExhibitorSocialMediaLink',
        ),
        migrations.DeleteModel(
            name='ExhibitorLink',
        ),
        migrations.DeleteModel(
            name='Exhibitor',
        ),
        migrations.DeleteModel(
            name='ExhibitorStaff',
        ),
        migrations.DeleteModel(
            name='ExhibitorView',
        ),
    ]
