# Generated by Django 6.0.7 on 2026-09-01 14:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_user_profile_picture_user_profile_picture_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxrule',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax rate'),
        ),
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='tax_rate_between_0_and_100'),
        ),
    ]
