# Generated by Django 6.0.7 on 2026-08-30 13:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0067_user_profile_picture_user_profile_picture_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gmailoauthcredential',
            new_name='base_gmailo_event_i_133776_idx',
            old_name='base_gmailo_event_i_6f0d0d_idx',
        ),
        migrations.RenameIndex(
            model_name='gmailoauthcredential',
            new_name='base_gmailo_is_acti_22cf9d_idx',
            old_name='base_gmailo_is_acti_0d8f8f_idx',
        ),
        migrations.AlterField(
            model_name='streamschedule',
            name='stream_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('hls', 'HLS')], default='youtube', max_length=50, verbose_name='Stream Type'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tax rate'),
        ),
        migrations.AlterField(
            model_name='team',
            name='can_video_manage_content',
            field=models.BooleanField(default=False, help_text='Create and edit stages and chat/video channels; edit and delete rooms.', verbose_name='Video: Can manage rooms and content'),
        ),
    ]
