# Generated by Django 6.0.7 on 2026-08-31 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_rename_base_gmailo_event_i_6f0d0d_idx_base_gmailo_event_i_133776_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='taxrule',
            constraint=models.CheckConstraint(condition=models.Q(('rate__gte', 0), ('rate__lte', 100)), name='tax_rate_between_0_and_100'),
        ),
    ]
