# Generated by Django 6.0.7 on 2026-09-02 12:40

import os
import django.db.models.deletion
import eventyay.base.models.base
import i18nfield.fields
from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
from django.db import migrations, models


DEFAULT_PRESETS = [
    {
        'category': 'Abstract',
        'name': 'Abstract Spheres',
        'filename': 'abstract-spheres.jpg',
    },
    {
        'category': 'Gradients',
        'name': 'Sunset Gradient',
        'filename': 'gradient-sunset.jpg',
    },
    {
        'category': 'Social',
        'name': 'Social Gathering',
        'filename': 'social-gathering.jpg',
    },
    {
        'category': 'Technology',
        'name': 'Tech Mesh',
        'filename': 'tech-mesh.jpg',
    },
]


def seed_default_presets(apps, schema_editor):
    EventHeaderPresetCategory = apps.get_model('base', 'EventHeaderPresetCategory')
    EventHeaderPreset = apps.get_model('base', 'EventHeaderPreset')

    base_dir = getattr(settings, 'BASE_DIR', None)
    candidate_dirs = [
        os.path.join(str(base_dir), 'eventyay', 'static', 'eventyay-common', 'images', 'header_presets') if base_dir else '',
        os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'static', 'eventyay-common', 'images', 'header_presets')),
        '/usr/src/app/eventyay/static/eventyay-common/images/header_presets',
    ]

    static_preset_dir = None
    for candidate in candidate_dirs:
        if candidate and os.path.isdir(candidate):
            static_preset_dir = candidate
            break

    for item in DEFAULT_PRESETS:
        category, _ = EventHeaderPresetCategory.objects.get_or_create(
            name=item['category']
        )
        if EventHeaderPreset.objects.filter(category=category, name=item['name']).exists():
            continue

        filename = item['filename']
        image_storage_path = f'header_presets/{filename}'
        thumb_storage_path = f'header_presets/thumbs/{filename}'

        if static_preset_dir:
            full_source = os.path.join(static_preset_dir, filename)
            thumb_source = os.path.join(static_preset_dir, 'thumbs', filename)

            if os.path.isfile(full_source) and not default_storage.exists(image_storage_path):
                with open(full_source, 'rb') as f:
                    default_storage.save(image_storage_path, ContentFile(f.read()))

            if os.path.isfile(thumb_source) and not default_storage.exists(thumb_storage_path):
                with open(thumb_source, 'rb') as f:
                    default_storage.save(thumb_storage_path, ContentFile(f.read()))

        EventHeaderPreset.objects.create(
            category=category,
            name=item['name'],
            image=image_storage_path,
            thumbnail=thumb_storage_path,
            is_active=True,
        )


def rollback_default_presets(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_taxrule_tax_rate_bounds'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHeaderPresetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(max_length=100, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Header preset category',
                'verbose_name_plural': 'Header preset categories',
                'ordering': ['id'],
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.CreateModel(
            name='EventHeaderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(max_length=150, verbose_name='Preset name')),
                ('image', models.FileField(max_length=255, upload_to='header_presets/', verbose_name='Full-size image (1920 × 640 px)')),
                ('thumbnail', models.FileField(blank=True, max_length=255, null=True, upload_to='header_presets/thumbs/', verbose_name='Thumbnail image (400 × 133 px)')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, this preset will not appear in the event creation gallery.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='base.eventheaderpresetcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event header preset',
                'verbose_name_plural': 'Event header presets',
                'ordering': ['id'],
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.RunPython(
            seed_default_presets,
            reverse_code=rollback_default_presets,
        ),
    ]
