# Generated by Django 6.0.7 on 2026-09-05

import django.db.models.deletion
import eventyay.base.models.loungemesh
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_global_plugin_config_classification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StreamingServer',
        ),
        migrations.CreateModel(
            name='LoungeMeshAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(default=eventyay.base.models.loungemesh.default_token, max_length=128, unique=True)),
                ('moderator', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='LoungeMeshServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=300)),
                ('api_secret', models.CharField(blank=True, max_length=300)),
                ('jitsi_app_id', models.CharField(blank=True, max_length=200)),
                ('jitsi_app_secret', models.CharField(blank=True, max_length=300)),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='streamschedule',
            name='stream_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('vimeo', 'Vimeo'), ('hls', 'HLS')], default='youtube', max_length=50, verbose_name='Stream Type'),
        ),
        migrations.AlterField(
            model_name='team',
            name='can_video_manage_content',
            field=models.BooleanField(default=False, help_text='Create and edit stages and chat/video channels; edit and delete rooms.', verbose_name='Video: Can manage rooms and content'),
        ),
        migrations.AddField(
            model_name='loungemeshaccesstoken',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to='base.event'),
        ),
        migrations.AddField(
            model_name='loungemeshaccesstoken',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to='base.room'),
        ),
        migrations.AddField(
            model_name='loungemeshaccesstoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loungemeshserver',
            name='event_exclusive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.event'),
        ),
        migrations.AddIndex(
            model_name='loungemeshaccesstoken',
            index=models.Index(fields=['token', 'expires'], name='base_lounge_token_82a916_idx'),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='bbb_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='bbb_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='janus_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='janus_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='jitsi_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='jitsi_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='loungemeshserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='loungemesh_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='loungemeshserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='loungemesh_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='turn_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='turn_servers', to='base.organizer'),
        ),
    ]
