# Generated by Django 6.0.7 on 2026-09-14 11:16

import django.db.models.deletion
import eventyay.base.models.loungemesh
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_sync_model_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoungeMeshAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('token', models.CharField(default=eventyay.base.models.loungemesh.default_token, max_length=128, unique=True)),
                ('moderator', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to='base.event')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to='base.room')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loungemesh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoungeMeshServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('url', models.URLField(max_length=300)),
                ('api_secret', models.CharField(blank=True, max_length=300)),
                ('jitsi_app_id', models.CharField(blank=True, max_length=200)),
                ('jitsi_app_secret', models.CharField(blank=True, max_length=300)),
                ('cost', models.IntegerField(default=0)),
                ('event_exclusive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.event')),
                ('events', models.ManyToManyField(blank=True, related_name='loungemesh_servers', to='base.event')),
                ('organizers', models.ManyToManyField(blank=True, related_name='loungemesh_servers', to='base.organizer')),
            ],
        ),
        migrations.RemoveField(
            model_name='roulettepairing',
            name='room',
        ),
        migrations.RemoveField(
            model_name='roulettepairing',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='roulettepairing',
            name='user2',
        ),
        migrations.AlterUniqueTogether(
            name='rouletterequest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rouletterequest',
            name='room',
        ),
        migrations.RemoveField(
            model_name='rouletterequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='StreamingServer',
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='bbb_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='bbbserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='bbb_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='janus_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='janus_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='jitsi_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='jitsi_servers', to='base.organizer'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='turn_servers', to='base.event'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='organizers',
            field=models.ManyToManyField(blank=True, related_name='turn_servers', to='base.organizer'),
        ),
        migrations.AlterField(
            model_name='event',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', '\u200eDeutsch (German)'), ('de-formal', '\u200eDeutsch (German (formal))'), ('ar', '\u200eاَلْعَرَبِيَّةُ (Arabic)'), ('bg', '\u200eБългарски (Bulgarian)'), ('bn', '\u200eবাংলা (Bengali)'), ('ca', '\u200eCatalà (Catalan)'), ('cs', '\u200eČeština (Czech)'), ('da', '\u200eDansk (Danish)'), ('el', '\u200eΕλληνικά (Greek)'), ('es', '\u200eEspañol (Spanish)'), ('fa-ir', '\u200eقارسی (Persian)'), ('fi', '\u200eSuomi (Finnish)'), ('fr', '\u200eFrançais (French)'), ('hu', '\u200eMagyar (Hungarian)'), ('hi', '\u200eहिन्दी (Hindi)'), ('gu', '\u200eગુજરાતી (Gujarati)'), ('id', '\u200eBahasa Indonesia (Indonesian)'), ('it', '\u200eItaliano (Italian)'), ('ja-jp', '\u200e日本語 (Japanese)'), ('ko', '\u200e한국어 (Korean)'), ('km', '\u200eខ្មែរ (Khmer)'), ('lv', '\u200eLatviešu (Latvian)'), ('ms', '\u200eBahasa Melayu (Malay)'), ('ml', '\u200eമലയാളം (Malayalam)'), ('mr', '\u200eमराठी (Marathi)'), ('nb-no', '\u200eNorsk bokmål (Norwegian Bokmål)'), ('nl', '\u200eNederlands (Dutch)'), ('nl-informal', '\u200eNederlands (Dutch (informal))'), ('pl', '\u200ePolski (Polish)'), ('pl-informal', '\u200ePolski (nieformalny) (Polish (informal))'), ('pt-br', '\u200ePortuguês brasileiro (Brazilian Portuguese)'), ('pt-pt', '\u200ePortuguês (Portuguese)'), ('ro', '\u200eRomână (Romanian)'), ('ru', '\u200eРусский (Russian)'), ('si', '\u200eසිංහල (Sinhala)'), ('sl', '\u200eSlovenščina (Slovenian)'), ('sv', '\u200eSvenska (Swedish)'), ('sw', '\u200eKiswahili (Swahili)'), ('ta', '\u200eதமிழ் (Tamil)'), ('te', '\u200eతెలుగు (Telugu)'), ('th', '\u200eไทย (Thai)'), ('tr', '\u200eTürkçe (Turkish)'), ('uk', '\u200eУкраїнська (Ukrainian)'), ('ur', '\u200eاردو (Urdu)'), ('vi', '\u200eTiếng Việt (Vietnamese)'), ('zh-hans', '\u200e简体中文 (Chinese Simplified)'), ('zh-hant', '\u200e繁體中文 (Chinese Traditional)')], default='en', max_length=32, verbose_name='Default language'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('N', 'Number'), ('S', 'Text (one line)'), ('T', 'Multiline text'), ('B', 'Confirm Checkbox'), ('C', 'Radio button (Choose one option)'), ('L', 'Dropdown (Choose one option)'), ('M', 'Checkbox (Choose one or several options)'), ('F', 'File upload'), ('D', 'Date'), ('H', 'Time'), ('W', 'Date and time'), ('CC', 'Country code (ISO 3166-1 alpha-2)'), ('TEL', 'Phone number'), ('DES', 'Text field'), ('URL', 'URL')], max_length=5, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='talkquestion',
            name='variant',
            field=models.CharField(choices=[('number', 'Number'), ('string', 'Text (one-line)'), ('text', 'Multi-line text'), ('url', 'URL'), ('video', 'Video link'), ('date', 'Date'), ('datetime', 'Date and time'), ('boolean', 'Confirmation'), ('file', 'File upload'), ('choices', 'Radio button (Choose one option)'), ('multiple_choice', 'Checkbox (Choose one or several options)'), ('select', 'Select (one option)'), ('country', 'Country List'), ('tel', 'Phone number')], default='string', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(choices=[('en', 'English'), ('en-us', 'English (United States)'), ('en-gb', 'English (United Kingdom)'), ('en-au', 'English (Australia)'), ('en-ca', 'English (Canada)'), ('de', '\u200eDeutsch (German)'), ('de-formal', '\u200eDeutsch (German (formal))'), ('ar', '\u200eاَلْعَرَبِيَّةُ (Arabic)'), ('bg', '\u200eБългарски (Bulgarian)'), ('bn', '\u200eবাংলা (Bengali)'), ('ca', '\u200eCatalà (Catalan)'), ('cs', '\u200eČeština (Czech)'), ('da', '\u200eDansk (Danish)'), ('el', '\u200eΕλληνικά (Greek)'), ('es', '\u200eEspañol (Spanish)'), ('fa-ir', '\u200eقارسی (Persian)'), ('fi', '\u200eSuomi (Finnish)'), ('fr', '\u200eFrançais (French)'), ('hu', '\u200eMagyar (Hungarian)'), ('hi', '\u200eहिन्दी (Hindi)'), ('gu', '\u200eગુજરાતી (Gujarati)'), ('id', '\u200eBahasa Indonesia (Indonesian)'), ('it', '\u200eItaliano (Italian)'), ('ja-jp', '\u200e日本語 (Japanese)'), ('ko', '\u200e한국어 (Korean)'), ('km', '\u200eខ្មែរ (Khmer)'), ('lv', '\u200eLatviešu (Latvian)'), ('ms', '\u200eBahasa Melayu (Malay)'), ('ml', '\u200eമലയാളം (Malayalam)'), ('mr', '\u200eमराठी (Marathi)'), ('nb-no', '\u200eNorsk bokmål (Norwegian Bokmål)'), ('nl', '\u200eNederlands (Dutch)'), ('nl-informal', '\u200eNederlands (Dutch (informal))'), ('pl', '\u200ePolski (Polish)'), ('pl-informal', '\u200ePolski (nieformalny) (Polish (informal))'), ('pt-br', '\u200ePortuguês brasileiro (Brazilian Portuguese)'), ('pt-pt', '\u200ePortuguês (Portuguese)'), ('ro', '\u200eRomână (Romanian)'), ('ru', '\u200eРусский (Russian)'), ('si', '\u200eසිංහල (Sinhala)'), ('sl', '\u200eSlovenščina (Slovenian)'), ('sv', '\u200eSvenska (Swedish)'), ('sw', '\u200eKiswahili (Swahili)'), ('ta', '\u200eதமிழ் (Tamil)'), ('te', '\u200eతెలుగు (Telugu)'), ('th', '\u200eไทย (Thai)'), ('tr', '\u200eTürkçe (Turkish)'), ('uk', '\u200eУкраїнська (Ukrainian)'), ('ur', '\u200eاردو (Urdu)'), ('vi', '\u200eTiếng Việt (Vietnamese)'), ('zh-hans', '\u200e简体中文 (Chinese Simplified)'), ('zh-hant', '\u200e繁體中文 (Chinese Traditional)')], default='en', max_length=50, verbose_name='Language'),
        ),
        migrations.DeleteModel(
            name='RoulettePairing',
        ),
        migrations.DeleteModel(
            name='RouletteRequest',
        ),
        migrations.AddIndex(
            model_name='loungemeshaccesstoken',
            index=models.Index(fields=['token', 'expires'], name='base_lounge_token_82a916_idx'),
        ),
    ]
