# Generated by Django 6.0.7 on 2026-09-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_loungemeshaccesstoken_loungemeshserver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbbserver',
            name='disable_ssl',
            field=models.BooleanField(default=False, help_text='Allow non-HTTPS or bypass SSL verification for self-signed certificates.', verbose_name='Disable SSL enforcement'),
        ),
        migrations.AddField(
            model_name='janusserver',
            name='disable_ssl',
            field=models.BooleanField(default=False, help_text='Allow non-WSS/WS or bypass SSL verification for self-signed certificates.', verbose_name='Disable SSL enforcement'),
        ),
        migrations.AddField(
            model_name='jitsiserver',
            name='disable_ssl',
            field=models.BooleanField(default=False, help_text='Allow non-HTTPS/HTTP or bypass SSL verification for self-signed certificates.', verbose_name='Disable SSL enforcement'),
        ),
        migrations.AddField(
            model_name='turnserver',
            name='disable_ssl',
            field=models.BooleanField(default=False, help_text='Allow non-TLS/STUN or bypass SSL verification.', verbose_name='Disable SSL enforcement'),
        ),
    ]
