# Generated by Django 6.0.7 on 2026-09-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_privacy_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thirdpartyservice',
            name='data_processed',
            field=models.TextField(blank=True, help_text='What personal data the service receives, e.g. IP address, email address.', verbose_name='Data processed'),
        ),
        migrations.AddField(
            model_name='thirdpartyservice',
            name='dpa_status',
            field=models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('signed', 'Signed')], default='not_required', max_length=20, verbose_name='DPA status'),
        ),
        migrations.AddField(
            model_name='thirdpartyservice',
            name='region',
            field=models.CharField(blank=True, help_text='Where the provider processes the data.', max_length=200, verbose_name='Country / region'),
        ),
    ]
