# Generated by Django 6.0.7 on 2026-09-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0074_bbbserver_disable_ssl_janusserver_disable_ssl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='all_addons_included',
            field=models.BooleanField(default=False, verbose_name='Offer all add-on products for free when redeeming this voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='all_bundles_included',
            field=models.BooleanField(default=False, verbose_name='Include all bundled products without a designated price when redeeming this voucher'),
        ),
    ]
