# Generated by Django 6.0.7 on 2026-09-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_voucher_limit_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='all_addons_included',
            field=models.BooleanField(default=False, verbose_name='Offer all add-on products for free when redeeming this voucher'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='all_bundles_included',
            field=models.BooleanField(default=False, verbose_name='Include all bundled products without a designated price when redeeming this voucher'),
        ),
        migrations.AddConstraint(
            model_name='voucher',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('budget__isnull', True),
                    models.Q(('all_addons_included', False), ('all_bundles_included', False)),
                    _connector='OR',
                ),
                name='voucher_budget_not_with_included_products',
            ),
        ),
    ]
