# Generated by Django 6.0.7 on 2026-09-20 04:49

from django.db import migrations


def add_default_speaker_questions(apps, schema_editor):
    from eventyay.base.models.cfp import create_default_speaker_questions
    from django_scopes import scope

    Event = apps.get_model('base', 'Event')
    for event in Event.objects.all().only('id', 'slug'):
        try:
            from eventyay.base.models import Event as LiveEvent
            live_event = LiveEvent.objects.get(pk=event.pk)
            create_default_speaker_questions(live_event)
        except Exception:
            import traceback
            traceback.print_exc()

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_voucher_limit_products'),
    ]

    operations = [
        migrations.RunPython(
            add_default_speaker_questions,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
