# Generated by Django 6.0.7 on 2026-09-23 06:25

import i18nfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_productvariation_admission_validity_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminemailqueue',
            name='message',
            field=i18nfield.fields.I18nTextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='adminemailqueue',
            name='subject',
            field=i18nfield.fields.I18nCharField(max_length=500, verbose_name='Subject'),
        ),
    ]
