# Generated by Django 6.0.7 on 2026-09-20 08:55

import django.db.models.deletion
import django.db.models.functions.text
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models

import eventyay.base.models.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_productvariation_admission_validity_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Speaker email')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Speaker name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=16)),
                ('mail_state', models.CharField(choices=[('not_sent', 'Not sent'), ('queued', 'Queued in Outbox'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_sent', max_length=16)),
                ('accepted', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.queuedmail')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speaker_invitations', to='base.submission')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speaker_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
                'constraints': [models.UniqueConstraint(models.F('submission'), django.db.models.functions.text.Lower('email'), name='unique_speaker_invitation_per_submission')],
            },
            bases=(eventyay.base.models.mixins.LogMixin, eventyay.base.models.mixins.FileCleanupMixin, rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
