# Generated by Django 6.0.7 on 2026-09-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_productvariation_admission_validity_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerprofile',
            name='job_title',
            field=models.CharField(blank=True, help_text='What is your official job title?', max_length=255, null=True, verbose_name='Job title/role'),
        ),
        migrations.AddField(
            model_name='speakerprofile',
            name='organization',
            field=models.CharField(blank=True, help_text='What organization or company do you represent?', max_length=255, null=True, verbose_name='Organization'),
        ),
    ]
