# Generated by Django 6.0.7 on 2026-09-26 12:53

from django.db import migrations


def make_events_public_and_indexed(apps, schema_editor):
    Event = apps.get_model('base', 'Event')
    Event_SettingsStore = apps.get_model('base', 'Event_SettingsStore')

    meetup_ids = list(
        Event_SettingsStore.objects.filter(key='event_type', value='meetup').values_list(
            'object_id', flat=True
        )
    )

    Event.objects.filter(is_public=False).exclude(pk__in=meetup_ids).update(is_public=True)

    Event_SettingsStore.objects.filter(key='meta_noindex').exclude(
        object_id__in=meetup_ids
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_speakerprofile_job_title_speakerprofile_organization'),
    ]

    operations = [
        migrations.RunPython(
            make_events_public_and_indexed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
