# Generated by Django 6.0.8 on 2026-10-06 13:57

import os
from django.conf import settings
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage
import django.core.validators
import django.db.models.deletion
import eventyay.base.models.base
import eventyay.base.validators
import i18nfield.fields
from django.db import migrations, models

DEFAULT_PRESETS = [
    {
        'category': 'Abstract',
        'name': 'Abstract Spheres',
        'filename': 'abstract-spheres.jpg',
    },
    {
        'category': 'Gradients',
        'name': 'Sunset Gradient',
        'filename': 'gradient-sunset.jpg',
    },
    {
        'category': 'Social',
        'name': 'Social Gathering',
        'filename': 'social-gathering.jpg',
    },
    {
        'category': 'Technology',
        'name': 'Tech Mesh',
        'filename': 'tech-mesh.jpg',
    },
]


def seed_default_presets(apps, schema_editor):
    EventHeaderPresetCategory = apps.get_model('base', 'EventHeaderPresetCategory')
    EventHeaderPreset = apps.get_model('base', 'EventHeaderPreset')

    base_dir = getattr(settings, 'BASE_DIR', None)
    candidate_dirs = [
        os.path.join(str(base_dir), 'eventyay', 'static', 'eventyay-common', 'images', 'header_presets') if base_dir else '',
        os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'static', 'eventyay-common', 'images', 'header_presets')),
        '/usr/src/app/eventyay/static/eventyay-common/images/header_presets',
    ]

    static_preset_dir = None
    for candidate in candidate_dirs:
        if candidate and os.path.isdir(candidate):
            static_preset_dir = candidate
            break

    for item in DEFAULT_PRESETS:
        filename = item['filename']
        image_storage_path = f'header_presets/{filename}'
        thumb_storage_path = f'header_presets/thumbs/{filename}'

        files_valid = False
        if static_preset_dir:
            full_source = os.path.join(static_preset_dir, filename)
            thumb_source = os.path.join(static_preset_dir, 'thumbs', filename)

            if os.path.isfile(full_source) and os.path.isfile(thumb_source):
                if not default_storage.exists(image_storage_path):
                    with open(full_source, 'rb') as f:
                        default_storage.save(image_storage_path, ContentFile(f.read()))

                if not default_storage.exists(thumb_storage_path):
                    with open(thumb_source, 'rb') as f:
                        default_storage.save(thumb_storage_path, ContentFile(f.read()))

                files_valid = True

        if not files_valid:
            files_valid = default_storage.exists(image_storage_path) and default_storage.exists(thumb_storage_path)

        if files_valid:
            category, _ = EventHeaderPresetCategory.objects.get_or_create(
                name=item['category']
            )
            if not EventHeaderPreset.objects.filter(category=category, name=item['name']).exists():
                EventHeaderPreset.objects.create(
                    category=category,
                    name=item['name'],
                    image=image_storage_path,
                    thumbnail=thumb_storage_path,
                    is_active=True,
                )


def rollback_default_presets(apps, schema_editor):
    EventHeaderPreset = apps.get_model('base', 'EventHeaderPreset')

    for item in DEFAULT_PRESETS:
        presets = EventHeaderPreset.objects.filter(name=item['name'])
        for preset in presets:
            if preset.image and default_storage.exists(preset.image.name):
                default_storage.delete(preset.image.name)
            if preset.thumbnail and default_storage.exists(preset.thumbnail.name):
                default_storage.delete(preset.thumbnail.name)


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_voucher_all_addons_bundles_included'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventHeaderPresetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(max_length=100, verbose_name='Category name')),
            ],
            options={
                'verbose_name': 'Header preset category',
                'verbose_name_plural': 'Header preset categories',
                'ordering': ['id'],
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(db_index=True, help_text='Should be short, only contain lowercase letters, numbers, dots, and dashes, and must be unique among your events. We recommend some kind of abbreviation or a date with less than 10 characters that can be easily remembered, but you can also choose to use a random value. This will be used in URLs, order codes, invoice numbers, and bank transfer references.', max_length=50, validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?\\Z'), eventyay.base.validators.EventSlugBanlistValidator()], verbose_name='Short form'),
        ),
        migrations.AlterField(
            model_name='organizer',
            name='slug',
            field=models.CharField(db_index=True, help_text='Should be short, only contain lowercase letters, numbers, dots, and dashes. Every slug can only be used once. This is being used in URLs to refer to your organizer accounts and your events.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='The slug may only contain letters, numbers, dots and dashes.', regex='^[a-zA-Z0-9](?:[a-zA-Z0-9.-]*[a-zA-Z0-9])?\\Z'), eventyay.base.validators.OrganizerSlugBanlistValidator()], verbose_name='Short form'),
        ),
        migrations.AlterField(
            model_name='productvariation',
            name='admission_validity_mode',
            field=models.CharField(blank=True, choices=[('inherit', 'Same as product'), ('', 'No check-in time restriction'), ('fixed', 'Fixed start and end'), ('subevent', 'Valid during assigned event date'), ('event', 'Valid during entire event')], default='inherit', help_text='Use "Same as product" to inherit the product mode and overlay only the variation fields you set. Choose "No check-in time restriction" to explicitly clear a product-level restriction for this variation.', max_length=20, verbose_name='Admission validity mode'),
        ),
        migrations.AlterField(
            model_name='track',
            name='color',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^#([0-9A-Fa-f]{3}){1,2}$')], verbose_name='Color'),
        ),
        migrations.CreateModel(
            name='EventHeaderPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', i18nfield.fields.I18nCharField(max_length=150, verbose_name='Preset name')),
                ('image', models.FileField(max_length=255, upload_to='header_presets/', verbose_name='Full-size image (1920 × 640 px)')),
                ('thumbnail', models.FileField(blank=True, max_length=255, null=True, upload_to='header_presets/thumbs/', verbose_name='Thumbnail image (400 × 133 px)')),
                ('is_active', models.BooleanField(default=True, help_text='If disabled, this preset will not appear in the event creation gallery.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presets', to='base.eventheaderpresetcategory', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Event header preset',
                'verbose_name_plural': 'Event header presets',
                'ordering': ['id'],
            },
            bases=(models.Model, eventyay.base.models.base.LoggingMixin),
        ),
        migrations.RunPython(
            seed_default_presets,
            reverse_code=rollback_default_presets,
        ),
    ]
