# Generated by Django on 2026-10-07

from django.db import migrations, models
import django.db.models.functions.comparison


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_voucher_all_addons_bundles_included'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                django.db.models.functions.comparison.Coalesce('last_login', 'date_joined'),
                name='user_last_accessed_idx',
            ),
        ),
    ]
